sudo: false

language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
  
cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]] && [[ $TRAVIS_JDK_VERSION = openjdk15 ]]; then GOAL=deploy; else GOAL=package; fi
  - echo $GOAL
  - mvn -U $GOAL
