sudo: false

language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
  
cache:
  directories:
    - "$HOME/.m2/repository"

script: mvn -U deploy
