#
# Copyright © 2013-2018, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

logging:
  level: INFO

web:
  server:
    port: 443
    https: true

crypto:
  keystores:
    master:
      path: src/main/resources/master.jks
      password: kspasswd
      aliases:
        ssl:
          password: clientpasswd
