logging:
  level: INFO

application:
  id: oauth-sample

rest:
  path: /api

security:
  realms: OAuthRealm
  web:
    urls:
      - pattern: /profile.html
        filters: oauth
      - pattern: /callback
        filters: oauthCallback
      - pattern: /api/**
        filters: oauth
  oauth:
    discoveryDocument: https://accounts.google.com/.well-known/openid-configuration
    redirect: http://localhost:8080/callback
    scopes: [email, openid, profile]
    clientId: 234443717825-hmtqfehreoc59hnhso80cl648ujec4to.apps.googleusercontent.com
    clientSecret: Ad9k0wCHtvKLytDVt7lLMPy0
